version: '3'
services:
  php:
    build:
      context: ../../
      dockerfile: .configuration/docker/php/Dockerfile
    container_name: docker_php_microservice
    volumes:
      - ../../application:/var/www/html
      - ../.env:/var/www/html/.env
    extra_hosts:
      - host.docker.internal:host-gateway
      - mysql:host-gateway
    networks:
      - mynetwork
#    command: ["cron", "-f"]

  nginx:
    build:
      context: ../../
      dockerfile: .configuration/docker/nginx/Dockerfile
    container_name: docker_nginx_microservice
    ports:
      - "8080:80"
    volumes:
      - ../../application:/var/www/html`
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    extra_hosts:
      - host.docker.internal:host-gateway
      - mysql:host-gateway
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: docker_mysql_microservice
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice
      MYSQL_USER: testUser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ../../mysql_data:/var/lib/mysql

networks:
  mynetwork:

volumes:
  mysql_data:
